services:

#  xmpp-server:
#    container_name: spring-xmpp-websocket-server
#    image: smartinrub/spring-xmpp-websocket-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - spring-mysql
#      - spring-mongo
#      - openfire
#      
#  spring-mysql:
#    container_name: spring-mysql
#    image: mysql/mysql-server:latest
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: smarthealth
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 0000
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#      
  spring-mongo:
    container_name: spring-mongo
    image: mongo:4.1
    ports:
      - 27017:27017
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 0000
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017
    
    
  spring-redis:   
    container_name: spring-redis                  
    image: redis:5.0.5-alpine       
    ports:
      - '6379:6379'
    restart: always
    
#  openfire-mysql:
#    container_name: openfire-mysql
#    image: mysql/mysql-server:latest
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: openfire
#      MYSQL_USER: openfireuser
#      MYSQL_PASSWORD: openfirepasswd
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#      
#  openfire:
#    container_name: openfire
#    image: quantumobject/docker-openfire
#    ports:
#      - "9090:9090"
#      - "5222:5222"
#      - "5269:5269"
#      - "5223:5223"
#      - "7443:7443"
#      - "7777:7777"
#      - "7070:7070"
#      - "5229:5229"
#      - "5275:5275"
#    depends_on:
#      - openfire-mysql
